n.usachev lab1.1
Ripper1233/engischool-nsu-oop-2022 pull request #6
Opened 2022-10-07 20:38 UTC by nikitaI7

2022-10-08 22:55 UTC, Ripper1233 requested changes

2022-10-08 22:55 UTC, Ripper1233 commented on Complex.cpp
> +    }
> Combined constructor with one argument and with two arguments into constructor with two arguments:  
>     Complex(double) Complex(double, double) -> Complex(double, double)

Очень хорошо! Как можно ещё сократить число конструкторов? Какое минимальное количество конструкторов нужно реализовывать для поддержи функционала из задания?

2022-10-08 22:55 UTC, Ripper1233 commented on README.md
> +      copy constructor Complex(const Complex &)
Не нашёл его. Имеется ввиду, что он дефолтный? Или Вы решили не реализовывать его?

2022-10-08 22:55 UTC, Ripper1233 commented on README.md
> +    friend istream & operator >> (istream &, const Complex &);
Это не дополнительный функционал. 

>  Operator overload ostream & operator<< (ostream &, const Complex &)  
>  Operator overload istream & operator>> (ostream &, const Complex &)

 Вы не можете перегрузить вот эти два оператора внутри класса, их в любом случае нужно делать `friend`

2022-10-08 22:55 UTC, Ripper1233 commented on Complex.cpp
> +std::istream & operator >> (std::istream &in, Complex &tmp)
Давайте "приклеивать" амперсанд к имени типа. И уберём пробелы между `operator` и самими операторами.

2022-10-08 22:55 UTC, Ripper1233 commented on Complex.cpp
> +    }
Бинарные арифметические, логические, побитовые операторы, операторы сравнения, присваивания (в т. ч. составные) отделяются пробелами.

2022-10-08 22:55 UTC, Ripper1233 commented on Complex.cpp
> +    Complex b(4,-4);
И после запятой тоже пробел.

2022-10-08 22:55 UTC, Ripper1233 commented on Complex.cpp
> +    std::cout << a << b << d << std::endl;
Вывод в духе `(7, 3)(4, -4)(3, 0)` не очень красивый. Добавьте пробел после закрывающей скобки.

2022-10-08 22:55 UTC, Ripper1233 commented on Complex.cpp
> +int main()
Функцию `main()` как и тестовый функционал - тоже в отдельный исходник.

2022-10-08 22:55 UTC, Ripper1233 commented on README.md
> +      copy constructor Complex(const Complex &)
Ну и если он есть/будет, то вот его можно в доп функционал

2022-10-08 22:55 UTC, Ripper1233 commented on README.md
> +<pre>
А что делает этот тег? Форматирование текста как код?

2022-10-10 09:59 UTC, Ripper1233 requested changes
Отсутствует CMakeLists.txt. Не забудьте ответить на вопрос о сборке программы. И вообще, не забывайте писать в conversation, особенно если я что-то спрашиваю.

2022-10-10 09:59 UTC, Ripper1233 commented on Complex.cpp
> +        k = a / ((tmp.re * tmp.re) + 1);
Зачем здесь + 1?

2022-10-10 09:59 UTC, Ripper1233 commented on Complex.cpp
> +    return Complex(tmp.re * k, tmp.im * k);
А зачем вообще определять знаки подобным образом?

2022-10-10 09:59 UTC, Ripper1233 commented on Complex.cpp
> +}
Обобщая замечания выше, функция просто ужасна, код как будто написан студентами-индусами, да ещё и работает не правильно. Я не говорю про какие-то сложные примеры, банальное 1 / (1 + i) уже не верно. Впрочем, даже Ваш собственный пример, 1 / a, где a - это Complex(1, 0), т.е. вещественная единица, тоже не верен. Что навевает на мысли, а запускали ли Вы этот код перед сдачей, проверяли ли его? Переделать.

2022-10-10 09:59 UTC, Ripper1233 commented on README.md
> +    ostream& operator<<(ostream&, const Complex&)
Во-первых, это не доп функционал, он есть в описании лабораторной работы. Во-вторых, оператор << должен работать так, как он и работал раньше и работает сейчас: выводить комплексное число в алгебраической форме или как пару вещественных чисел. Вы должны реализовать отдельный метод, который будет выводить число в показательной форме, z = r * e^(i * phi).

2022-10-10 09:59 UTC, Ripper1233 commented on main.cpp
> +#include <iostream>
Как у Вас это вообще компилируется? Опишите, как Вы собираете программу.

2022-10-10 09:59 UTC, Ripper1233 commented on main.cpp
> +int main()
Где возврат функции? Указано, что она возвращает int

2022-10-10 09:59 UTC, Ripper1233 commented on Complex.cpp
> +}
Реализация неправильная. Переделать.

2022-10-10 22:07 UTC, nikitaI7 commented on README.md
> +<pre>
Да, он он форматирует текст как код

2022-10-10 22:19 UTC, nikitaI7 commented on main.cpp
> +int main()
исправлю

2022-10-10 22:20 UTC, nikitaI7 commented on main.cpp
> +#include <iostream>
опишу в readme

2022-10-10 22:31 UTC, nikitaI7 commented on Complex.cpp
> +}
код я запускал, скорее всего я изначально как то неправильно считал

2022-10-10 22:34 UTC, nikitaI7 commented on Complex.cpp
> +}
я более грамотно все переделал

2022-10-11 20:24 UTC, Ripper1233 requested changes
После исправления можно обсудить. Время обсудим позже.

2022-10-11 20:24 UTC, Ripper1233 commented on Complex.cpp
> +    return ! Complex::operator==(tmp);
`Complex::` здесь избыточно, Вы и так находитесь в классе.

2022-10-11 20:24 UTC, Ripper1233 commented on main.cpp
> +#include <iostream>
Хм, наверное include guard помогает. Ладно, это ещё обсудим.

2022-10-11 20:24 UTC, Ripper1233 commented on Complex.cpp
> +#include "math.h"
math.h - устаревший хедер из C. Используйте cmath.

2022-10-17 07:26 UTC, Ripper1233 approved these changes

2022-10-19 12:55 UTC, closed without merging